feature: реализация ТЗ по спринту 13
SmirnovSA1/java-shareit pull request #1
Opened 2024-04-29 18:22 UTC by SmirnovSA1

реализация ТЗ по спринту 13

2024-04-30 09:01 UTC, andrew-larkin requested changes
Привет! Отличный старт! Структурно все выполнено правильно, остается местами внести кое-какие правки, и работа будет принята.

2024-04-30 09:01 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +//    @ExceptionHandler
закомментированный код удаляем

2024-04-30 09:01 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
для этого приложения давай добавим библиотеку mapStruct - она используется на всех реальных проектах, будет очень полезно ее изучить. Все методы маппинга будут писаться в одну строчку благодаря ней, и нам это очень облегчит работу над этим приложением в ближайших спринтах

2024-04-30 09:01 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
в классах-моделях лучше не использовать @Data - она некорректно рассчитывает хэш. Можно заменить ее на @Getter, @Setter и т.д.

2024-04-30 09:01 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader(name = "X-Sharer-User-Id") Long userId,
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.createItem(itemDto, userId));
Для всех методов во всех контроллерах стоит его добавить

2024-04-30 09:01 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return ItemMapper.toItemDto(createdItem);
непосредственный маппинг лучше делать прямо в сервисе. контроллер должен заниматься только маршрутизацией запросов

2024-04-30 14:55 UTC, SmirnovSA1 commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +//    @ExceptionHandler
Удалил закомментированный код

2024-04-30 14:56 UTC, SmirnovSA1 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
Добавил библиотеку mapStruct и настроить для совместно работы с lombok. Также изменил класс ItemMapper на интерфейс с добавлением используемых методов, чтобы библиотека могла сгенерировать в target класс-реализацию.

2024-04-30 14:56 UTC, SmirnovSA1 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
Заменил аннотацию @Data на отдельные @Getter, @Setter, @ToString, @EqualsAndHashCode по рекомендации.
Но я не совсем понимаю некорректность расчета хэша при аннотации @Data, может сможешь более подробно "на пальцах" объяснить?)

2024-04-30 14:56 UTC, SmirnovSA1 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader(name = "X-Sharer-User-Id") Long userId,
Добавил новый класс-обертку в методы контроллера.

2024-04-30 14:56 UTC, SmirnovSA1 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return ItemMapper.toItemDto(createdItem);
Весь маппинг вынес в слой сервиса.

2024-05-01 09:08 UTC, andrew-larkin approved these changes
Привет! Отлично, работа принята!

2024-05-01 09:11 UTC, merged